[2021-05-23 02:02:25,113] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_apple_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 02:02:25,159] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_apple_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 02:02:25,160] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 02:02:25,161] {taskinstance.py:867} INFO - Starting attempt 1 of 3
[2021-05-23 02:02:25,162] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 02:02:25,185] {taskinstance.py:887} INFO - Executing <Task(BashOperator): move_apple_data_to_diff_location> on 2021-05-21T18:00:00+00:00
[2021-05-23 02:02:25,198] {standard_task_runner.py:53} INFO - Started process 551 to run task
[2021-05-23 02:02:25,335] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: marketvol.move_apple_data_to_diff_location 2021-05-21T18:00:00+00:00 [running]> c240d08e6ad5
[2021-05-23 02:02:25,390] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-05-23 02:02:25,400] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmp8c4mv3b5/move_apple_data_to_diff_locationo54qxsvk
[2021-05-23 02:02:25,401] {bash_operator.py:115} INFO - Running command: 
    mv $DATAPATH/2021-05-21/data_aapl.csv  /usr/local/finance_data/2021-05-21
[2021-05-23 02:02:25,415] {bash_operator.py:122} INFO - Output:
[2021-05-23 02:02:25,449] {bash_operator.py:130} INFO - Command exited with return code 0
[2021-05-23 02:02:25,466] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=marketvol, task_id=move_apple_data_to_diff_location, execution_date=20210521T180000, start_date=20210523T020225, end_date=20210523T020225
[2021-05-23 02:02:35,049] {logging_mixin.py:112} INFO - [2021-05-23 02:02:35,049] {local_task_job.py:103} INFO - Task exited with return code 0
[2021-05-23 04:51:32,680] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_apple_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 04:51:32,716] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_apple_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 04:51:32,717] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 04:51:32,718] {taskinstance.py:867} INFO - Starting attempt 1 of 3
[2021-05-23 04:51:32,719] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 04:51:32,726] {taskinstance.py:887} INFO - Executing <Task(BashOperator): move_apple_data_to_diff_location> on 2021-05-21T18:00:00+00:00
[2021-05-23 04:51:32,733] {standard_task_runner.py:53} INFO - Started process 413 to run task
[2021-05-23 04:51:32,842] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: marketvol.move_apple_data_to_diff_location 2021-05-21T18:00:00+00:00 [running]> 67459f5d81d7
[2021-05-23 04:51:32,895] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-05-23 04:51:32,898] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpcxdnmcg8/move_apple_data_to_diff_location7qh_q8jn
[2021-05-23 04:51:32,899] {bash_operator.py:115} INFO - Running command: 
    mv $DATAPATH/2021-05-21/data_aapl.csv  /usr/local/finance_data/2021-05-21
[2021-05-23 04:51:32,919] {bash_operator.py:122} INFO - Output:
[2021-05-23 04:51:32,948] {bash_operator.py:126} INFO - mv: cannot create regular file '/usr/local/finance_data/2021-05-21': Permission denied
[2021-05-23 04:51:32,950] {bash_operator.py:130} INFO - Command exited with return code 1
[2021-05-23 04:51:32,973] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2021-05-23 04:51:32,980] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-05-23 04:51:42,627] {logging_mixin.py:112} INFO - [2021-05-23 04:51:42,626] {local_task_job.py:103} INFO - Task exited with return code 1
